CREATE DATABASE IF NOT EXISTS pdf_saas;
USE pdf_saas;
CREATE TABLE IF NOT EXISTS users(id INT AUTO_INCREMENT PRIMARY KEY,name VARCHAR(100),email VARCHAR(200),password_hash VARCHAR(200),folder_slug VARCHAR(64));
CREATE TABLE IF NOT EXISTS documents(id INT AUTO_INCREMENT PRIMARY KEY,user_id INT,filename VARCHAR(200),original_name VARCHAR(200),size_bytes BIGINT,mime VARCHAR(80),sha256 CHAR(64));
